content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /home/5/
    #    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.template.context_processors import static
from django.urls import path, include
from django.conf.urls.static import static

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('content/', include('content.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('bagis/', views.bagis, name='bagis'),
    path('aidat/', views.aidat, name='aidat'),
    path('hizmetlerimiz/', views.hizmetlerimiz, name='hizmetlerimiz'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),
    path('category/<int:id>/<slug:slug>/', views.category_contents, name='category_contents'),
    path('content/<int:id>/<slug:slug>/', views.content_detail, name='content_detail'),
    path('search/', views.content_search, name='content_search'),
    path('search_auto/', views.content_search_auto, name='content_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),
    path('menu/<int:id>', views.menu, name='menu'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),

]

content/models.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm, TextInput, Select, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey
from lib2to3.fixes.fix_idioms import TYPE


class Menu(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    link = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return '>>'.join(full_path[::-1])


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=30)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Content(models.Model):
    TYPE = (
        ('menu', 'menu'),
        ('haber', 'haber'),
        ('duyuru', 'duyuru'),
        ('etkinlik', 'etkinlik'),

    )
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    menu = models.OneToOneField(Menu, null=True, blank=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=TYPE)
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'

    def catimg_tag(self):
        return mark_safe((Category.status))

    def get_absolute_url(self):
        return reverse('content_detail', kwargs={'slug': self.slug})


class Images(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayir'),
    )
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def _str_(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment']


class ContentForm(ModelForm):
    class Meta:
        model = Content
        fields = ['category', 'title', 'slug', 'keywords', 'description', 'image', 'detail']
        widgets = {
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'category': Select(attrs={'class': 'input', 'placeholder': 'city'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'detail': CKEditorWidget(),

        }


class ContentImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title', 'image']


class AnasayfaIcerik(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'

    def catimg_tag(self):
        return mark_safe((Category.status))

    def get_absolute_url(self):
        return reverse('content_detail', kwargs={'slug': self.slug})

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayir'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(blank=True, max_length=255)
    company = models.CharField(blank=True, max_length=150)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField()
    services = RichTextUploadingField()
    contact = RichTextUploadingField()
    referances = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeorder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeorder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeorder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'input', 'placeorder': 'Your Message', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + '[' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayir'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10,choices=STATUS)
    create_at = models.DateTimeField (auto_now_add=True)
    update_at = models.DateTimeField (auto_now=True)

    def __str__(self):
        return self.question

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    catid = forms.IntegerField()

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name')
    email = forms.EmailField(max_length=200, label='Email')
    first_name = forms.CharField(max_length=30, help_text='Firs Name', label='First Name')
    last_name = forms.CharField(max_length=30,  help_text='Last Name', label='Last Name')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

content/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from content.models import CommentForm, Comment


def index(request):
    return HttpResponse("Content Page")


@login_required(login_url='/login')
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':  # form post edildiyse
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user
            data = Comment()
            data.user_id = current_user.id
            data.content_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Yorumunuz başarıyla gönderildi.")
            return HttpResponseRedirect(url)
    messages.warning(request, "Yorumunuz gönderilemedi. Lütfen kontrol ediniz.")
    return HttpResponseRedirect(url)

home/templates/aidat.html
{% extends "homebase.html" %}

{% block title %}  {{ setting.company }}  {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>

{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">Aidat</a></li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div>
                {% include "sidebar.html" %}
            </div>
        </div>
        <div class="col-md-8">

            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        AİDAT
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-xs-4">
                        Kart Sahibi: <input type="text" class="sinif" id="kartSahibi" maxlength="25" size="25"
                                            placeholder="Adınızı Girin...">
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-xs-1">
                        Kart No: <input type="text" class="sinif" id="a" maxlength="4" size="4" placeholder="* * * *">
                    </div>
                    --
                    <div class="col-xs-1">
                        <input type="text" class="sinif" id="b" maxlength="4" size="4" placeholder="* * * *">
                    </div>
                    --
                    <div class="col-xs-1">
                        <input type="text" class="sinif" id="c" maxlength="4" size="4" placeholder="* * * *">
                    </div>
                    --
                    <div class="col-xs-1">
                        <input type="text" class="sinif" id="d" maxlength="4" size="4" placeholder="* * * *">
                    </div>
                    <div class="col-xs-9">
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-md-2">
                        CVV: <input type="text" class="sinif" id="cvv" maxlength="3" size="3" placeholder="CVV">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <button class="btn" type="submit">ÖDEME YAP</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    </div>
                </div>
            </div>


        </div>
    </div>
    <br> <br> <br><br><br>
</div>
{% endblock %}

home/templates/bagis.html
{% extends "homebase.html" %}

{% block title %}  {{ setting.company }}  {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>

{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">Bağış</a></li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4">
             <div>
                  {% include "sidebar.html" %}
            </div>
        </div>
        <div class="col-md-8">

            <!--
EDITED BY ILYAS TAYSUN
e-mail: eylesa@gmail.com
-->
<div class="container">
  <div class="row">
    <div class="col-md-12">
     BAĞIŞ
    </div>
  </div>
  <br />
   <div class="row">
    <div class="col-xs-4">
      Kart Sahibi: <input type="text" class="sinif" id="kartSahibi"  maxlength="25" size="25" placeholder="Adınızı Girin...">
    </div>
  </div>
  <br />
  <div class="row">
      <div class="col-xs-1">
        Kart No: <input type="text" class="sinif" id="a"  maxlength="4" size="4" placeholder="* * * *">
        </div> --
      <div class="col-xs-1">
        <input type="text" class="sinif" id="b"  maxlength="4" size="4" placeholder="* * * *">
        </div> --
      <div class="col-xs-1">
        <input type="text" class="sinif" id="c"  maxlength="4" size="4" placeholder="* * * *">
        </div> --
      <div class="col-xs-1">
        <input type="text" class="sinif" id="d"  maxlength="4" size="4" placeholder="* * * *">
        </div>
      <div class="col-xs-9">
      </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-2">
      CVV: <input type="text" class="sinif" id="cvv"  maxlength="3" size="3" placeholder="CVV">
    </div>
  </div>
    <br>
  <div class="row">
    <div class="col-md-12">
      <button class="btn" type="submit">BAĞIŞ YAP</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>

        </div>
    </div>
     <br> <br> <br><br><br>
</div>
{% endblock %}

home/templates/content_detail.html
{% extends "homebase.html" %}

{% block title %}  {{ setting.company }} / {{ content.title }} {% endblock %}
{% block keywords %} {{ content.keywords }} {% endblock %}
{% block description %} {{ content.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active"><a
                    href="/category/{{ content.category_id }}/{{ content.category.slug }}">{{ content.category }}</a>
            </li>
            <li class="breadcrumb-item active">{{ content.title }}</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Product Detail Start -->
<div class="product-detail">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3">
                <div class="product-detail-top">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="product-slider-single normal-slider">
                                <img src="{{ content.image.url }}" alt="Product Image">
                                {% for rs in images %}
                                <div class="slider-nav-img"><img src="{{ rs.image.url }}" alt="Product Image"></div>
                                {% endfor %}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="col-md-12">
                    <div class="tab-content">
                        <div id="description" class="container tab-pane active">
                            <p>{{ content.title }}</p>
                            <p>{{ content.detail |safe }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-6">
                   <div class="" style="color:white; background-color:#FF6F61; text-align: center;">
                       <h4>Yorumlar</h4>
                   </div>
                    <br>
                    {% for rs in comments %}
                    <div class="single-review">
                        <div class="review-heading">
                            <div><a href="#"><i class="fa fa-user-o"></i><b>{{ rs.user.username }}</b>
                            </a></div>
                            <div><a href="#"><i class="fa fa-clock-o"></i>{{ rs.create_at}}
                            </a></div>
                        </div>
                        <div class="review-body"><h4>{{ rs.subject }}</h4>
                            <b>{{ rs.comment }}</b>
                        </div>
                    </div>
                    <br> <br>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-6">
                     <div class="" style="color:white; background-color:#FF6F61; text-align: center;">
                       <h4>Yorum Yap</h4>
                   </div>
                    <br>
                    <div class="row form">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <form class="review-form"
                              action="/content/addcomment/{{ content.id }}"
                              method="POST">
                            {% csrf_token %}
                            <div class="col-sm-6">
                                <input class="input" type="text" name="subject"
                                       id="id_subject"
                                       placeholder="Konu"></input>
                            </div>
                            <br>
                            <div class="col-sm-12">
                                                <textarea class="input" name="comment" id="id_comment"
                                                          placeholder="Yorum Yap" rows="5" cols="50"></textarea>
                            </div>
                            {% if user.id is not None %}
                            <div class="col-sm-12">
                                <button>Gönder</button>
                                {% else %}
                                Yorum yapabilmek için <a href="/login">Giriş</a> yapın.
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Product Detail End -->
{% endblock %}

home/templates/menu_content.html
{% extends "homebase.html" %}

{% block title %}  {{ setting.company }} / {{ content.title }} {% endblock %}
{% block keywords %} {{ content.keywords }} {% endblock %}
{% block description %} {{ content.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active"><a
                    href="/category/{{ content.category_id }}/{{ content.category.slug }}">{{ content.category }}</a>
            </li>
            <li class="breadcrumb-item active">{{ content.title }}</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Product Detail Start -->
<div class="product-detail">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4">
                <div class="product-detail-top">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="product-slider-single normal-slider">
                                <img src="{{ content.image.url }}" alt="Product Image">
                                {% for rs in images %}
                                <div class="slider-nav-img"><img src="{{ rs.image.url }}" alt="Product Image"></div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="col-md-12">
                    <div class="tab-content">
                        <div id="description" class="container tab-pane active">
                            <p>{{ content.title }}</p>
                            <p>{{ content.detail |safe }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-6">
                   <div class="" style="color:white; background-color:#FF6F61; text-align: center;">
                       <h4>Yorumlar</h4>
                   </div>
                    <br>
                    {% for rs in comments %}
                    <div class="single-review">
                        <div class="review-heading">
                            <div><a href="#"><i class="fa fa-user-o"></i><b>{{ rs.user.username }}</b>
                            </a></div>
                            <div><a href="#"><i class="fa fa-clock-o"></i>{{ rs.create_at}}
                            </a></div>
                        </div>
                        <div class="review-body"><h4>{{ rs.subject }}</h4>
                            <b>{{ rs.comment }}</b>
                        </div>
                    </div>
                    <br> <br>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-6">
                     <div class="" style="color:white; background-color:#FF6F61; text-align: center;">
                       <h4>Yorum Yap</h4>
                   </div>
                    <br>
                    <div class="row form">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <form class="review-form"
                              action="/content/addcomment/{{ content.id }}"
                              method="POST">
                            {% csrf_token %}
                            <div class="col-sm-6">
                                <input class="input" type="text" name="subject"
                                       id="id_subject"
                                       placeholder="Konu"></input>
                            </div>
                            <br>
                            <div class="col-sm-12">
                                                <textarea class="input" name="comment" id="id_comment"
                                                          placeholder="Yorum Yap" rows="10" cols="50"></textarea>
                            </div>
                            {% if user.id is not None %}
                            <div class="col-sm-12">
                                <button>Gönder</button>
                                {% else %}
                                Yorum yapabilmek için <a href="/login">Giriş</a> yapın.
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Product Detail End -->
{% endblock %}