mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.template.context_processors import static
from django.urls import path, include
from django.conf.urls.static import static

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('content/', include('content.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('bagis/', views.bagis, name='bagis'),
    path('aidat/', views.aidat, name='aidat'),
    path('hizmetlerimiz/', views.hizmetlerimiz, name='hizmetlerimiz'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),
    path('category/<int:id>/<slug:slug>/', views.category_contents, name='category_contents'),
    path('content/<int:id>/<slug:slug>/', views.content_detail, name='content_detail'),
    path('search/', views.content_search, name='content_search'),
    path('search_auto/', views.content_search_auto, name='content_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),
    path('menu/<int:id>', views.menu, name='menu'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayir'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(blank=True, max_length=255)
    company = models.CharField(blank=True, max_length=150)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField()
    services = RichTextUploadingField()
    contact = RichTextUploadingField()
    referances = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeorder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeorder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeorder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'input', 'placeorder': 'Your Message', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + '[' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayir'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10,choices=STATUS)
    create_at = models.DateTimeField (auto_now_add=True)
    update_at = models.DateTimeField (auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Select, FileInput

from home.models import UserProfile


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),

        }

CITY = [
    ('Istanbul', 'Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir', 'Izmir'),

]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),

        }

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from content.models import Category, Comment, Content, ContentForm, ContentImageForm, Images, Menu
from home.models import UserProfile, Setting
from user.forms import ProfileUpdateForm, UserUpdateForm


@login_required(login_url='/login')
def index(request):
    category = Category.objects.all()
    setting = Setting.objects.get()
    menu = Menu.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'category': category,
               'profile': profile,
               'setting' : setting,
               'menu': menu,
               }
    return render(request, 'user_profile.html', context)


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('/user')
    else:
        category = Category.objects.all()
        setting = Setting.objects.get()
        menu = Menu.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,
            'setting' : setting,
            'menu': menu,

        }
        return render(request, 'user_update.html', context)


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Parola güncelleme başarılı')
            return HttpResponseRedirect('/user')
        else:
            messages.success(request, 'Please correct the error below.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        setting = Setting.objects.get()
        menu = Menu.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html',
                      {
                          'form': form,
                          'category': category,
                          'setting' : setting,
                          'menu': menu,
                      })


@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    setting = Setting.objects.get()
    menu = Menu.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'comments': comments,
        'setting' : setting,
        'menu': menu,
    }
    return render(request, 'user_comments.html', context)


@login_required(login_url='/login')
def deletecomment(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.error(request, 'Comment deleted.')
    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def contents(request):
    category = Category.objects.all()
    setting = Setting.objects.get()
    menu = Menu.objects.all()
    current_user = request.user
    contents = Content.objects.all()
    context = {
        'category': category,
        'contents': contents,
        'setting' : setting,
        'menu': menu,
    }
    return render(request, 'user_contents.html', context)


@login_required(login_url='/login')
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Content()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.category = form.cleaned_data['category']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            return HttpResponseRedirect('/user/contents')
        else:
            return HttpResponseRedirect('/user/addcontent')
    else:
        category = Category.objects.all()
        setting = Setting.objects.get()
        menu = Menu.objects.all()
        form = ContentForm()
        context = {
            'category': category,
            'form': form,
            'setting' : setting,
            'menu': menu,
        }
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def contents(request):
    category = Category.objects.all()
    setting = Setting.objects.get()
    menu = Menu.objects.all()
    current_user = request.user
    contents = Content.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'contents': contents,
        'setting' : setting,
        'menu': menu,
    }
    return render(request, 'user_contents.html', context)


@login_required(login_url='/login')
def contentedit(request, id):
    content = Content.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/user/contents')
        else:
            return HttpResponseRedirect('/user/contentedit/' + str(id))
    else:
        category = Category.objects.all()
        setting = Setting.objects.get()
        menu = Menu.objects.all()
        form = ContentForm(instance=content)
        context = {
            'category': category,
            'form': form,
            'setting' : setting,
            'menu': menu,
        }
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def contentdelete(request, id):
    current_user = request.user
    Content.objects.filter(id=id, user_id=current_user.id).delete()
    return HttpResponseRedirect('/user/contents')


def contentaddimage(request, id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = ContentImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.content_id = id
            data.image = form.cleaned_data['image']
            data.save()
            return HttpResponseRedirect(lasturl)
        else:
            return HttpResponseRedirect(lasturl)
    else:
        content = Content.objects.get(id=id)
        images = Images.objects.filter(content_id=id)
        form = ContentImageForm()
    context = {
        'content': content,
        'form': form,
        'images': images,
    }
    return render(request, 'content_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %} {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">Parola Güncelle</a></li>

        </ul>
    </div>
</div>
<!-- Breadcrumb End -->


<div class="my-account">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                {% include "user_panel.html" %}
            </div>
            <div class="col-md-9">
                <section class="ftco-section ftco-degree-bg">

                    {% if messages %}
                        {% for message in messages %}
                            <div style="color:#d43f3a; font-size:medium">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post">
                        {% csrf_token %}

                        {% for field in form %}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                            <small style="color:grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in fields.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </p>
                        {% endfor %}
                        <button class="primary-btn" type="submit">Save Changes</button>
                    </form>
                </section>
            </div>
        </div>
    </div>
</div>

{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title> Content Gallery </title>

</head>
<body class="goto-here">
<h2>{{ content.title }}</h2>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">
    {{ message|safe }}
</div>
{% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="content_id" id="id_content_id" value="{{ content.id }}">
    <label for="id_tittle"> Title:</label>
    <input type="text" name="title" class="input" placeholder="tittle" maxlength="50" id="id_title">
<label for="id_tittle"> Image:</label>
<input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_image">
<button class="primary-btn" type="submit">Upload Image</button>

</form>

<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">
{% endfor %}


</body>
</html>

user/templates/user_addcontent.html
{% extends "homebase.html" %}

{% block title %} {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% load static %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">İçerik Ekle</a></li>

        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<div class="my-account">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                {% include "user_panel.html" %}
            </div>
            <div class="col-md-9">

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form.media }}
                        {{ form.as_p }}
                    </fieldset>
                    <div class="form-group">
                        <button class="primary-btn" type="submit">SAVE</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>


{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %} {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">Yorumlarım</a></li>

        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<div class="my-account">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                {% include "user_panel.html" %}
            </div>
            <div class="col-md-9">
                <div class="tab-content">

                    <div class="tab-pane fade show active" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="thead-dark">

                                <tr>
                                    <th>Image</th>
                                    <th>Content</th>
                                    <th>Subject</th>
                                    <th>Comment</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                    <th>Detail</th>
                                </tr>
                                {% for rs in comments %}
                                <tr>
                                    <td><a href="/content/{{ rs.content_id }}/{{ rs.content.slug }}"><img src="{{ rs.content.image.url }}" width="100px" height="80px"></a></td>
                                    <td><a href="/content/{{ rs.content_id }}/{{ rs.content.slug }}"><strong>{{ rs.content.title }}</strong></a></td>
                                    <td>{{ rs.subject }}</td>
                                    <td>{{ rs.comment }}</td>
                                    <td>{{ rs.status }}</td>
                                    <td>{{ rs.create_at }}</td>
                                    <td><a class="primary-btn" href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('Are you sure?')">Delete</a></td>
                                </tr>
                                {% endfor %}
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

user/templates/user_contents.html
{% extends "homebase.html" %}

{% block title %} {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">İçeriklerim</a></li>

        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<div class="my-account">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                {% include "user_panel.html" %}
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="section-title">
                        <button><a class="primary-btn" href="/user/addcontent">Add Content</a></button>
                    </div>
                    <div class="tab-pane fade show active" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="thead-dark">

                                <tr>
                                    <th>Image</th>
                                    <th>Title</th>
                                    <th>Galeri</th>
                                    <th>Category</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                </tr>
                                {% for rs in contents %}
                                <tr>
                                    <td><img
                                            src="{{ rs.image.url }}" width="100px" height="80px"></td>
                                    <td>{{ rs.title }}</td>
                                    <td>
                                        <a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}', 'galeri', 'height=600,width=800,top=50,left=150')">Galeri</a>
                                    </td>
                                    <td>{{ rs.category.title }}</td>
                                    <td>{{ rs.status }}</td>
                                    <td>{{ rs.create_at }}</td>
                                    <td><a class="primary-btn" href="/user/contentedit/{{ rs.id }}"
                                           onclick="return confirm('Are you sure?')">Edit</a></td>
                                    <td><a class="primary-btn" href="/user/contentdelete/{{ rs.id }}"
                                           onclick="return confirm('Are you sure?')">Delete</a></td>
                                </tr>
                                {% endfor %}
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

user/templates/user_panel.html
<div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
    <a class="nav-link" id="orders-nav" data-toggle="" href="/user" role="tab"><i
            class="	fa fa-address-card"></i>Kullanıcı Bilgileri</a>
    <a class="nav-link" id="payment-nav" data-toggle="" href="/user/comments" role="tab"><i
            class="fa fa-comments"></i>Yorumlarım</a>
    <a class="nav-link" id="address-nav" data-toggle="" href="/user/contents" role="tab"><i
            class="	fa fa-folder-open"></i>İçeriklerim</a>
    <a class="nav-link" href="/logout"><i class="fa fa-sign-out-alt"></i>Logout</a>
</div>

user/templates/user_profile.html
{% extends "homebase.html" %}

{% block title %}  {{ setting.company }}  {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}'>
{% endblock %}


{% block content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item"><a href="#">Kullanıcı Profili</a></li>

        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- My Account Start -->
<div class="my-account">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                {% include "user_panel.html" %}
            </div>
            <div class="col-md-9">
                <div class="tab-content">

                    <div class="tab-pane fade show active" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Profil Fotoğrafı</th>
                                    <td class="image-prod"><img src="{{ user.userprofile.image.url }}" width="100"
                                                                height="100"></td>
                                </tr>
                                <tr>
                                    <th>Username</th>
                                    <td>{{ profile.user.username }}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ profile.user.email }}</td>
                                </tr>
                                <tr>
                                    <th>Phone</th>
                                    <td> {{ profile.phone }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>Address</th>
                                    <td>
                                        {{ profile.address }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>City</th>
                                    <td>
                                        {{ profile.city }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>Country</th>

                                    <td> {{ profile.country }}</td>

                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td></td>
                                    <td>
                                        <button><a href="/user/update" class="primary-btn"
                                                   style="background-color:#FF6F61; color:white">Update Profile</a>
                                        </button>
                                        <button><a href="/user/password" class="primary-btn"
                                                   style="background-color:#FF6F61; color:white">Change Password</a>
                                        </button>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- My Account End -->

{% endblock %}